project:
  type: book
  output-dir: docs
book:
  title: "Center for Biodiversity Analysis: Gen3sis Workshop 2024"
  author: "Alexander Skeels and Oskar Hagen"
  date: "23.07.2024"
  chapters:
    - index.qmd
    - Day1_Prac1_setup.qmd
    - Day1_Prac2_basics.qmd
    - Day1_Prac3_islands.qmd
    - Day2_Prac4_outputs.qmd
    - Day2_Prac5_landscapes.qmd
    - Day3_Prac6_sandbox.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
editor: visual

