---
title: "👻 Important considerations"
---

### Paleo-environmental data

Investigations of deep-time paleoclimatic influences on biodiversity are still limited by our current mechanistic knowledge of eco-evolutionary processes and by computational power, as well as by the availability of paleo-environmental reconstructions ([Svenning et al., 2015](https://www.annualreviews.org/doi/abs/10.1146/annurev-ecolsys-112414-054314), [Franklin et al., 2017](https://scholar.google.ch/scholar?q=Big+data+for+forecasting+the+impacts+of+global+change+on+plant+communities.&hl=zh-CN&as_sdt=0&as_vis=1&oi=scholart), [Pontarp et al., 2019](https://www.sciencedirect.com/science/article/pii/S0169534718302805?casa_token=X2HR0EDV6csAAAAA:2FWB1soCJ0_4kllkds9pUiwYr4GVPaWhWAz3ELh8BIClJZ_E6k0LqoqQANSXRpySTkzScri6UxjU)). Biodiversity dynamics and climatic variations happening on smaller spatio-temporal scales have to be ignored due to the uncertainty in paleo-landscape reconstructions.

### Distribution, fossil and phylogenetic data

Biodiversity data is of the essence when evaluating implemented processes of eco-evolutionary models with empirical biodiversity patterns. In order to perform the evaluation, multiple past and present biological empirical datasets can be used, such as: (i) fossil records, (ii) calibrated molecular phylogenies, (iii) population genetic data, (iv) trait measurements, and (v) species distribution maps. The combination of multiple datasets, such as phylogenies and fossils, provides a better picture of past dynamic processes ([Huang et al., 2015](https://www.pnas.org/content/112/16/4903), [Hagen et al., 2018](https://academic.oup.com/sysbio/article/67/3/458/4563320?login=true), [Coiro et al., 2019](https://nph.onlinelibrary.wiley.com/doi/10.1111/nph.15708)). The main gaps remaining in biodiversity data, as pointed out in multiple studies ([Franklin, 2010](https://www.cambridge.org/core/books/mapping-species-distributions/58225AE5693AED8BD812F7CEBE35378A#), [Hampton et al., 2015](https://esajournals.onlinelibrary.wiley.com/doi/10.1890/ES14-00402.1), [Meyer et al., 2016](https://onlinelibrary.wiley.com/doi/full/10.1111/ele.12624?casa_token=kFuy9WzRyj4AAAAA%3ALVCEQOWfoFD_XCiTV2G5TacAJr1NWplmwHHR-h804vQxUyGZXFGyHpD0fCET0J7zWZGeFoBwwzgi2XFLvw)), are: (i) sparse data with regional biases, (ii) a lack of non-occurrence data reporting, (iii) poor availability of public data, and (iv) high heterogeneity in data quality and methodologies.

### Model complexity

The modelling engine *gen3sis* introduced here is predominantly a theoretical model rather than exclusively a calculating tool, since responses from possible natural processes are predicted ([Guisan and Zimmermann, 2000](https://www.sciencedirect.com/science/article/pii/S0304380000003549?casa_token=xd2OXKLoMdwAAAAA:aD_z2LqztsitPV3aDCLTjylXMbkEu1Qi7QSJ3VaZ-FT1A1Aqsnx3N9GDDAhq_pMsrn0k6sP4_Ydp)). By prioritizing theoretical correctness of the predicted response over predicted precision, a spatio-temporal mechanistic model was created in the most flexible way possible in order to explore multiple hypotheses and processes.

### Computational time

Runtimes are heavily dependent on the number of species emerging during a simulation and their geographical extent, and thus are highly dependent on the assumed model parameters and input landscape. The current state of optimizations is limited because no parallelization is implemented, as ease of maintenance and development are prioritized for this initial release.

### Core functions

Given the inherent computational limitations, *gen3sis* tries to incorporate all the processes at the level of geographical ranges of populations, as realistically as possible. However, the modelled objects are limited to geographic populations and species. Also, it is not possible to track cluster phylogenies. Moreover, there is no within-cell variation within a species.

### Caveats

-   **temporal behaviour:** No variables in *gen3sis* have an explicit temporal component. It is always **x/timestep**. That means that most processes will either speed up or slow down if one changes the temporal resolution of the input. For example, a configured rate of dispersal of 1/timestep can become 10/million years or 2/million years for simulations with 10 and 2 timesteps per million years respectively.

-   **raster inputs:** The behaviour of the species dispersal and geographic clustering depends on the spatial input resolution. Changing input resolution can have secondary effects. For example, a higher-resolution landscape input will have more cells. Not only will it be easier to reach neighbouring cells, but there will also be more chances for dispersal events to happen. As such there might be a non-linear dependency between dispersal values and input resolution.

-   **polar distortions:** Our distance calculations correct for the distance distortions raster-based data experiences towards the polar regions. This does lead to many small cells being close together in the polar regions. This makes dispersal a lot easier compared to equatorial cells in two ways. First, the dispersal distances are often enough to reach multiple neighbours. And second, since there are many more cells closed by, more dispersal events can happen.
