---
title: "Gen3sis outputs and Biodiversity Patterns"
author: "Alex Skeels and Oskar Hagen"
execute: 
  eval: FALSE
---

## Outputs and Biodiversity Patterns - Part 1: Exploring outputs

```{r}
library(gen3sis)
library(terra)
```

```{r}
output_dir <- "output/islands" 

sim <- readRDS(file.path(output_dir, "config_islands_simple_Day1Prac3_M1/sgen3sis.rds")) 

# look at what the simulation summary contains
names(sim)    

#### Visualize the outputs 
plot_summary(sim) 

# or just the richness
richness <- rast(sim$summary$`richness-final`, type="xyz")
plot(richness, col=gen3sis::color_richness(10))
```

```{r}
# plot diversity at 3 time slices 
timesteps <- c(20, 10, 0) 
par(mfrow = c(1, 3)) 
for (i in timesteps) {   
  landscape_i <- readRDS(file.path(output_dir, paste0("config_southamerica/landscapes/landscape_t_",                                                      i, ".rds")))   
  species_i <- readRDS(file.path(output_dir, paste0("config_southamerica/species/species_t_",                                                    i, ".rds")))   
  plot_richness(species_i, landscape_i) } 
#dev.off()
```

## Outputs and Biodiversity Patterns - Part 2: Island Biogeography

Lets dive even further into the outputs and see if the simulations we did yesterday offer any fundamental insights into island biogeography theory.
