---
title: "Output"
---

The simulation output has several components which together, or seperately, allow for all kinds of analyses of resulting biodiversity patterns.

# Generate presence-absence matrix

A presence/absence matrix is a commonly used format for performing ecological analyses, such as PD/MPD/MNTD in the *picante* package.

``` r
# first set the directory to the output folder   # then load in landscape and species obejct at the final timestep (will work for any timestep) setwd("landscapes") landscape <- readRDS("landscape_t_0.rds")  setwd("../species") species <- readRDS("species_t_0.rds")  # grid cell names all_cells <- rownames(landscape$coordinates)  # get 0 for absence and 1 for presence in each grid cell all_species_presence <- do.call( cbind, lapply(species, FUN = function(x) {ifelse(all_cells %in% names(x$abundance), 1, 0)}))  # colnames are species names colnames(all_species_presence ) <- unlist(lapply(species, function(x){x$id}))  # column bind with x/y coordinates  presence_absence_matrix <- cbind(landscape$coordinates, all_species_presence)
```

#  Calculate taxonomic & phylogenetic diversity

The first step in your analysis could for instance be to calculate mean species richness per grid cell.

``` r
# read in the richness object for the desired timestep richness <- readRDS("richness_t_0.rds")) richness_mean <- mean(richness, na.rm=T)  
```

Then you might want to look at indices of phylogenetic diversity.

``` r
# read in the phylogeny for the desired timestep phy <- try(read.nexus("phylogeny_t_0.nex")))  # to make the simulations comparable, you should probably rescale each of them using the following function  rescaleTree<-function(tree,scale){   tree$edge.length<-     tree$edge.length/max(nodeHeights(tree)[,2])*scale   return(tree) }  phy <- rescaleTree(phy, 1)  # now that you have a presence-absence matrix, you can calculate phylogenetic community  # metrics like Faith's PD, MPD, and MNTD  pd_estimate <- pd.query(phy, presence_absence_matrix, standardize = T) mpd_estimate <- mpd.query(phy, presence_absence_matrix, standardize = T) mntd_estimate <- mpd.query(phy, presence_absence_matrix, standardize = T)
```

# Calculate functional diversity

One amazing feature of *gen3sis* is the possibility to let traits evolve with your simulation. The traits are defined in your core functions and can be anything, temperature niche, body size, or the number of limbs. The world is your oyster! To draw meaningful conclusions from your experiment you might have to

``` r
# load in the traits from the desired time step traits <- readRDS("traits_t_0.rds"))  # transform from a list into a readable vector   temp_trait_means <- unlist(lapply(traits, FUN=function(x){y=mean(x[,"temp"], na.rm=T);return(y)})) # this is the temperature niche    bs_trait_means <- unlist(lapply(traits, FUN=function(x){y=mean(x[,"body_size"], na.rm=T);return(y)})) # and this represents bodysize   # exploring different summary statistics of the same metrics  temp_mean<- mean(temp_trait_means, na.rm=T) # mean temp niche  temp_sd <- sd(temp_trait_means, na.rm=T) # sd temp niche  temp_skewness[i] <- skewness(temp_trait_means, na.rm=T)     bs_mean<- mean(bs_trait_means, na.rm=T) # mean temp niche  bs_sd <- sd(bs_trait_means, na.rm=T) # sd temp niche
```

# Calculate batch of spatial, phylogenetic, and functional metrics

This [script](https://gitlab.ethz.ch/ites-le/gen3sis/gen3sis_wiki/-/blob/master/tools/ESH_extract_summary_statistics.R) calculates a set of 53 summary statistics used in Skeels et al (2021) and gives an example of, not only how to calculate a variety of different metrics, but also how to do so on a large batch of simulations (here we loop over the output folders of 500 simulations).

# Calculate diversification rates through space and time

This [script](https://gitlab.ethz.ch/ites-le/gen3sis/gen3sis_wiki/-/blob/master/tools/DRTST_temperature.R) calculates speciation rates and extinction at each time step and also summarises speciation rates and extinction by both temperature and latitude to understand the spatial variation in diversification rates.

# Calculate phylogenetic and weighted endemisms

This [script](https://gitlab.ethz.ch/ites-le/gen3sis/gen3sis_wiki/-/blob/master/tools/phylogenetic_and_weighted_endemism.R) calculates phylogenetic and weighted endemism from simulated data.

# Standalone functions

Another way of organizing analysis tools is to have a set of functions similar to an R package that can be called in various scripts. Here is a [set of various example functions](https://gitlab.ethz.ch/ites-le/gen3sis/gen3sis_wiki/-/tree/master/tools/keggin) to use / look through.
