---
title: "Program"
execute: 
  eval: FALSE
---

# Day 1. {.unnumbered}

-   9:00 - Welcome (Platypus Room) - Introductions and Overview of Gen3sis Workshop

-   9:45 - Lecture 1. Oskar Hagen (Eucalyptus Room) - History and philosophy of simulation modelling in biodiversity studies

-   10:45 - Coffee Break

-   11:00 - Practical 1. Installation and Set Up (30mins - 1hr)

-   12pm - Practical 2. Gen3sis Config Basics

-   12:00 - Lunch Break

-   1:30 - Practical 2. Gen3sis Config Basics (continue - 2hrs)

-   15:30 - Coffee Break

-   15:45pm - Guided Exercise 1. Explore island configs

-   16:30 - Questions / Warp up Day 1

# Day. 2 {.unnumbered}

-   9am - Lecture 2. Alex and Oskar - Inference from biodiversity data

-   10:00 - Practical 3.1. Gen3sis outputs and biodiversity patterns

-   10:30 - Coffee Break

-   10:45 - Practical 3.2 Gen3sis outputs and biodiversity patterns (contd.)

-   12:30 - lunch

-   13:30 - Lecture 3. Tristan Salles -- Paleoenvironmental models and data

-   14:15 - Discussion

-   14:45 - Coffee break

-   15:00 - Practical 4. Modifying landscapes for Gen3sis

-   16:30 - Questions / Wrap up Day 2

# Day 3. {.unnumbered}

-   09:00 - Lecture 4. Alex and Oskar - Designing simulation experiments with Gen3sis

-   10:00 Group work - implementing models in Gen3sis

-   10:30 - Coffee Break

-   10:45 - Group work - implementing models in Gen3sis (contd.)

-   12:30 - Lunch break

-   13:30 - Wrapping up Group work

-   14:45 - Coffee Break

-   15:00 - Presenting models and warp up Day 3

-   16:00 - Pub
