{
  "hash": "40e3da8be8ea765f3957833496caee1f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"🖥️ Silicodiversity\"\nauthor: \"Alex Skeels and Oskar Hagen\"\nexecute: \n  eval: TRUE\n---\n\n\n## Exploring outputs {.unnumbered}\n\nIn this prac we will explore the files outputted from gen3sis using the island simulations we ran yesterday. We will learn how to manipule/wrange these data structures into formats used by common R packages for phylogenetic comparative methods, community phylogenetics, biogeography, etc.\n\nThe goal for today will be to produce:\n\n1.  A map of Species Richness from the simulation summary object\n\n2.  A plot of Lineages Through Time from the phylogeny\n\n3.  Plot of species trait values on a phylogenetic tree, by linking the species objects to the phylogeny\n\n4.  Maps of Phylogenetic Diversity by linking species objects to the landscape and phylogeny\n\nFirst, let's make sure we have the necessary packages loaded\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequire(gen3sis)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: gen3sis\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'gen3sis' was built under R version 4.2.3\n```\n\n\n:::\n\n```{.r .cell-code}\nrequire(terra)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: terra\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'terra' was built under R version 4.2.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nterra 1.7.29\n```\n\n\n:::\n\n```{.r .cell-code}\nrequire(ape)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: ape\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'ape'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:terra':\n\n    rotate, trans, zoom\n```\n\n\n:::\n\n```{.r .cell-code}\nrequire(phytools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: phytools\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'phytools' was built under R version 4.2.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: maps\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'maps' was built under R version 4.2.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'phytools'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:terra':\n\n    rescale\n```\n\n\n:::\n\n```{.r .cell-code}\nrequire(picante)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: picante\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'picante' was built under R version 4.2.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: vegan\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: permute\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: lattice\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis is vegan 2.6-4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'vegan'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:phytools':\n\n    scores\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: nlme\n```\n\n\n:::\n:::\n\n\n#### Simulation summary object (sgen3sis.rds) {.unnumbered}\n\nThe first object we will look at today is the sgenesis.rds file. This file contains a summary of the simulation. Which we can plot (as we did yesterday) with the plot_summary function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutput_dir <- \"output/islands\" \n\nsim <- readRDS(file.path(output_dir, \"config_islands_simple_Day1Prac3_M1/sgen3sis.rds\")) \n\n# look at what the simulation summary contains\nnames(sim) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"summary\"    \"flag\"       \"system\"     \"parameters\"\n```\n\n\n:::\n:::\n\n\nThe first element is the sim summary. This conatins a record of the history of speciation, extinction, and species richness through time (phylo_summary), a history of the number of total grid cells occupied during the simulation through time (occupancy) and the species richness of each grid cell at the final time step.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(sim$summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 3\n $ phylo_summary : num [1:52, 1:4] 4 4 4 4 4 4 4 4 4 4 ...\n  ..- attr(*, \"dimnames\")=List of 2\n  .. ..$ : chr [1:52] \"initial\" \"50\" \"49\" \"48\" ...\n  .. ..$ : chr [1:4] \"total\" \"alive\" \"speciations\" \"extinctions\"\n $ occupancy     : Named num [1:52] 1 0.382 0.39 0.365 0.358 ...\n  ..- attr(*, \"names\")= chr [1:52] \"initial\" \"50\" \"49\" \"48\" ...\n $ richness-final: num [1:3600, 1:3] 0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5 ...\n  ..- attr(*, \"dimnames\")=List of 2\n  .. ..$ : chr [1:3600] \"1\" \"2\" \"3\" \"4\" ...\n  .. ..$ : chr [1:3] \"x\" \"y\" \"0\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# phylo summary\nhead(sim$summary$phylo_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        total alive speciations extinctions\ninitial     4     4           4           0\n50          4     4           0           0\n49          4     4           0           0\n48          4     4           0           0\n47          4     4           0           0\n46          4     4           0           0\n```\n\n\n:::\n\n```{.r .cell-code}\n# occupancy\nhead(sim$summary$occupancy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  initial        50        49        48        47        46 \n1.0000000 0.3821464 0.3897485 0.3650047 0.3584392 0.3333333 \n```\n\n\n:::\n\n```{.r .cell-code}\n# occupancy\nhead(sim$summary$`richness-final`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    x    y 0\n1 0.5 59.5 0\n2 1.5 59.5 0\n3 2.5 59.5 0\n4 3.5 59.5 0\n5 4.5 59.5 0\n6 5.5 59.5 0\n```\n\n\n:::\n:::\n\n\nThese data are called on in the plot_summary function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize the outputs \nplot_summary(sim) \n```\n\n::: {.cell-output-display}\n![](Day2_Prac4_outputs_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nWe can also use these data to map out patterns of species richness\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make sure the landscape is loaded\nlc <- readRDS(file.path(\"data\", \"landscapes\", \"islands\",\"landscapes.rds\"))\n\n# can remove cells with elevation below sea level at timestep 0 (present-day) to see the outlines of the islands\nna_mask <- is.na(lc$elevation[,\"0\"])\nrich <- sim$summary$`richness-final`\nrich[na_mask,3] <- NA\n\n# turn richness summary into a raster \nrichness <- rast(rich, type=\"xyz\")\n\n# plot\nplot(richness, col=c(\"grey\", gen3sis::color_richness(12)))\n```\n\n::: {.cell-output-display}\n![](Day2_Prac4_outputs_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe next part of the simulation summary object is the flag which will tell us if the simulation ran successfully. It should give \"OK\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim$flag\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"OK\"\n```\n\n\n:::\n:::\n\n\nNext is the system summary. This is information about the R version, R packages, and operating system used in the simulation. This ensures complete repeatability. It also tells us the runtime of the simulation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim$system\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`runtime-hours`\n[1] 0.04024773\n\n$`gen3sis-version`\n[1] '1.5.11'\n\n$`R-version`\n               _                                \nplatform       x86_64-w64-mingw32               \narch           x86_64                           \nos             mingw32                          \ncrt            ucrt                             \nsystem         x86_64, mingw32                  \nstatus                                          \nmajor          4                                \nminor          2.2                              \nyear           2022                             \nmonth          10                               \nday            31                               \nsvn rev        83211                            \nlanguage       R                                \nversion.string R version 4.2.2 (2022-10-31 ucrt)\nnickname       Innocent and Trusting            \n\n$OS\n  sysname \n\"Windows\" \n\n$`session-information`\nR version 4.2.2 (2022-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n\nlocale:\n[1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8   \n[3] LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                      \n[5] LC_TIME=English_Australia.utf8    \n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] paleotree_3.4.5    diversitree_0.10-0 picante_1.8.2      nlme_3.1-160      \n [5] vegan_2.6-4        lattice_0.20-45    permute_0.9-7      phytools_2.1-1    \n [9] maps_3.4.1         ape_5.7-1          raster_3.6-26      sp_2.1-4          \n[13] terra_1.7-29       gen3sis_1.5.11    \n\nloaded via a namespace (and not attached):\n [1] phangorn_2.11.1         deSolve_1.35            subplex_1.8            \n [4] xfun_0.47               gdistance_1.6.4         splines_4.2.2          \n [7] vctrs_0.6.0             generics_0.1.3          expm_0.999-7           \n[10] mgcv_1.8-42             optimParallel_1.0-2     rlang_1.1.3            \n[13] glue_1.6.2              foreach_1.5.2           lifecycle_1.0.4        \n[16] stringr_1.5.1           combinat_0.0-8          codetools_0.2-19       \n[19] coda_0.19-4.1           knitr_1.48              doParallel_1.0.17      \n[22] parallel_4.2.2          Rcpp_1.0.10             clusterGeneration_1.3.8\n[25] jsonlite_1.8.8          scatterplot3d_0.3-44    fastmatch_1.1-3        \n[28] mnormt_2.1.1            png_0.1-8               digest_0.6.31          \n[31] stringi_1.7.12          numDeriv_2016.8-1.1     grid_4.2.2             \n[34] bitops_1.0-7            quadprog_1.5-8          cli_3.6.0              \n[37] tools_4.2.2             magrittr_2.0.3          RCurl_1.98-1.12        \n[40] cluster_2.1.4           pkgconfig_2.0.3         MASS_7.3-58.3          \n[43] Matrix_1.6-5            rstudioapi_0.14         iterators_1.0.14       \n[46] igraph_2.0.3            compiler_4.2.2         \n```\n\n\n:::\n:::\n\n\nFinally the summary object contains the config infromation and model parameters used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim$parameters\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$gen3sis\n$gen3sis$general\n$gen3sis$general$random_seed\n[1] 666\n\n$gen3sis$general$start_time\n[1] 50\n\n$gen3sis$general$end_time\n[1] 0\n\n$gen3sis$general$max_number_of_species\n[1] 50000\n\n$gen3sis$general$max_number_of_coexisting_species\n[1] 20000\n\n$gen3sis$general$end_of_timestep_observer\nfunction(data, vars, config){\n  plot_richness(data$all_species, data$landscape)\n  save_species() # saves a species and landscape objects for desired timesteps\n}\n<environment: 0x000001f7d5c74ac0>\n\n$gen3sis$general$trait_names\n[1] \"dispersal\"    \"temp_mean\"    \"temp_width\"   \"start_island\"\n\n$gen3sis$general$environmental_ranges\nlist()\n\n$gen3sis$general$verbose\n[1] 1\n\n\n$gen3sis$initialization\n$gen3sis$initialization$initial_abundance\n[1] 1\n\n$gen3sis$initialization$create_ancestor_species\nfunction(landscape, config) {\n  # browser()\n  co <- landscape$coordinates\n  sp1 <- co[which(co[,1]<20&co[,2]<30),]\n  sp2 <- co[which(co[,1]>20&co[,2]<30),]\n  sp3 <- co[which(co[,1]<20&co[,2]>30),]\n  sp4 <- co[which(co[,1]>20&co[,2]>30),]\n  \n  species_coords <- list(sp1,\n                         sp2,\n                         sp3,\n                         sp4)\n  new_species <- list()\n  \n  # Species 1 - high dispersal, low niche breadth\n  new_species[[1]] <- create_species(rownames(species_coords[[1]]), config)\n  new_species[[1]]$traits[ , \"dispersal\"] <- 5\n  new_species[[1]]$traits[ , \"temp_mean\"] <- mean(landscape$environment[rownames(species_coords[[1]]), \"mean_temp\"])\n  new_species[[1]]$traits[ , \"temp_width\"] <- 1\n  new_species[[1]]$traits[ , \"start_island\"] <- unique(landscape$environment[rownames(species_coords[[1]]), \"patch\"])\n  \n  # Species 2 - medium-high dispersal, medium-low niche breadth\n  new_species[[2]] <- create_species(rownames(species_coords[[2]]), config)\n  new_species[[2]]$traits[ , \"dispersal\"] <- 5\n  new_species[[2]]$traits[ , \"temp_mean\"] <- mean(landscape$environment[rownames(species_coords[[2]]), \"mean_temp\"])\n  new_species[[2]]$traits[ , \"temp_width\"] <- 1\n  new_species[[2]]$traits[ , \"start_island\"] <- unique(landscape$environment[rownames(species_coords[[2]]), \"patch\"])\n  \n  # Species 3 - medium-low dispersal, medium-high niche breadth\n  new_species[[3]] <- create_species(rownames(species_coords[[3]]), config)\n  new_species[[3]]$traits[ , \"dispersal\"] <- 5\n  new_species[[3]]$traits[ , \"temp_mean\"] <- mean(landscape$environment[rownames(species_coords[[3]]), \"mean_temp\"])\n  new_species[[3]]$traits[ , \"temp_width\"] <- 1\n  new_species[[3]]$traits[ , \"start_island\"] <- unique(landscape$environment[rownames(species_coords[[3]]), \"patch\"])\n  \n  # Species 4 -low dispersal,high niche breadth\n  new_species[[4]] <- create_species(rownames(species_coords[[4]]), config)\n  new_species[[4]]$traits[ , \"dispersal\"] <- 5\n  new_species[[4]]$traits[ , \"temp_mean\"] <- mean(landscape$environment[rownames(species_coords[[4]]), \"mean_temp\"])\n  new_species[[4]]$traits[ , \"temp_width\"] <- 1\n  new_species[[4]]$traits[ , \"start_island\"] <- unique(landscape$environment[rownames(species_coords[[4]]), \"patch\"])\n  return(new_species)\n}\n<environment: 0x000001f7d5c74ac0>\n\n\n$gen3sis$dispersal\n$gen3sis$dispersal$max_dispersal\n[1] Inf\n\n$gen3sis$dispersal$get_dispersal_values\nfunction(n, species, landscape, config){\n  values <- rexp(n, rate = 1/species$traits[,\"dispersal\"])\n  return(values)\n}\n<environment: 0x000001f7d5c74ac0>\n\n\n$gen3sis$speciation\n$gen3sis$speciation$divergence_threshold\n[1] 10\n\n$gen3sis$speciation$get_divergence_factor\nfunction(species, cluster_indices, landscape, config) {\n  return(1)\n}\n<environment: 0x000001f7d5c74ac0>\n\n\n$gen3sis$mutation\n$gen3sis$mutation$apply_evolution\nfunction(species, cluster_indices, landscape, config) {\n  # cell names\n  trait_evolutionary_power <-0.01\n  traits <- species[[\"traits\"]]\n  cells <- rownames(traits)\n  #homogenize trait based on abundance\n  # Homogenize all traits by weighted abundance, attention, exclude here any trait that should be more neutral\n  trn <- config$gen3sis$general$trait_names\n  for(cluster_index in unique(cluster_indices)){\n    # cluster_index <- 1\n    cells_cluster <- cells[which(cluster_indices == cluster_index)]\n    # hist(traits[cells_cluster, \"temp\"], main=\"before\")\n    mean_abd <- mean(species$abundance[cells_cluster])\n    weight_abd <- species$abundance[cells_cluster]/mean_abd\n    for (ti in trn){\n      traits[cells_cluster, ti] <- mean(traits[cells_cluster, ti]*weight_abd)\n    }\n    # hist(traits[cells_cluster, \"temp\"], main=\"after\")\n  }\n  \n  # mutate mean temperature\n  mutation_deltas <-rnorm(length(traits[, ti]), mean=0, sd=trait_evolutionary_power)\n  traits[, \"temp_mean\"] <- traits[, \"temp_mean\"] + mutation_deltas\n  return(traits)\n}\n<environment: 0x000001f7d5c74ac0>\n\n\n$gen3sis$ecology\n$gen3sis$ecology$apply_ecology\nfunction(abundance, traits, landscape, config) {\n  # get the difference between species and site mean temp\n  diff <- abs(traits[, \"temp_mean\"]-landscape[,\"mean_temp\"])\n  # set the abundance of species with a difference in mean temp larger than the species temp width to zero and the ones below to one\n  abundance[diff>traits[,\"temp_width\"]] <- 0\n  abundance[diff<=traits[,\"temp_width\"]] <- 1\n  return(abundance)\n}\n<environment: 0x000001f7d5c74ac0>\n\n\n\n$user\nlist()\n\n$directories\n$directories$input\n[1] \"data/landscapes/islands\"\n\n$directories$output\n[1] \"output/islands/config_islands_simple_Day1Prac3_M1\"\n\n$directories$output_plots\n[1] \"output/islands/config_islands_simple_Day1Prac3_M1/plots\"\n\n\nattr(,\"class\")\n[1] \"gen3sis_config\"\n```\n\n\n:::\n:::\n\n\n#### Phylogeny object (phy.nex) {.unnumbered}\n\nThe phylogeny object is pretty straight forward. It is a newxus file containing the relationships between the species.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read phy\nphy <- read.nexus(file.path(output_dir, \"config_islands_simple_Day1Prac3_M1/phy.nex\"))\n\n# plot phy\nplot(phy)\n```\n\n::: {.cell-output-display}\n![](Day2_Prac4_outputs_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nFrom this object we can look at lineages through time plots and estimate trends in diversification, such as using the gamma statistic to detect diversification slowdowns or speedups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot an ltt\nltt_M1 <-ltt(phy)\n```\n\n::: {.cell-output-display}\n![](Day2_Prac4_outputs_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# look at the gamma statistic\nprint(paste0(\"Gamma = \", round(ltt_M1$gamma, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Gamma = 0.88\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# is there a significant deviation from conatant rates?\nprint(paste0(\"P = \", round(ltt_M1$p, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"P = 0.38\"\n```\n\n\n:::\n:::\n\n\n#### Species objects (phy.nex) {.unnumbered}\n\nNow its time to get into the meat of the gen3sis outputs. Most of the infromation from the simulation is stored in the species objects. These are .rds files that contain a list which includes information on every species, extinct or extant, that existed during the simulation. We saved these at every time step. The naming convention is \"species_t_0.rds\" for time step 0 (present-day), and \"species_t_50\" for timestep 50, etc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load object\nspecies_t_0 <- readRDS(file.path(output_dir, \"config_islands_simple_Day1Prac3_M1\", \"species\", \"species_t_0.rds\"))\n\n# look at object class and length\nclass(species_t_0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"list\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(species_t_0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n\n```{.r .cell-code}\n# compare to number of tips in the phylogeny\nNtip(phy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n:::\n\n\nWe can see there are 14 elements in the list, representing our 14 species and this number matches the number of species in our phylogeny. No species went extinct in this particular simulation, but if they did, they would match extinct tips in the phylogeny.\n\nLets look at a single species\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(species_t_0[[1]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"id\"         \"abundance\"  \"traits\"     \"divergence\"\n```\n\n\n:::\n:::\n\n\nThe species has an ID which allows us to match it to the phylogeny.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspecies_t_0[[1]]$id\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1\"\n```\n\n\n:::\n:::\n\n\nThe species also has its abundances, which are linked to grid cells in the landscape which can matched with their names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspecies_t_0[[1]]$abundance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2767 2768 2769 2770 2771 2772 2773 2826 2827 2828 2830 2831 2832 2833 2886 2887 \n   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1 \n2891 2892 2893 2894 2895 2945 2946 2953 2954 2955 3004 3005 3015 3016 3063 3064 \n   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1 \n3076 3124 3125 3135 3136 3184 3185 3194 3195 3196 3245 3246 3254 3255 3305 3306 \n   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1 \n3307 3308 3312 3313 3314 3367 3368 3369 3370 3371 3372 3373 3429 3430 \n   1    1    1    1    1    1    1    1    1    1    1    1    1    1 \n```\n\n\n:::\n:::\n\n\nIn this case the species has abundance values of 1 in all populations from the cells that it occupies. Thyis is because we set abundances to be binary: 1=present, 0=absent. We can see the species occupies cells 2767,2768,2769, etc.\n\nThe species also has values of it's traits for each of those populations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(species_t_0[[1]]$traits)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     dispersal temp_mean temp_width start_island\n2767         5  21.12272          1            3\n2768         5  21.12585          1            3\n2769         5  21.11691          1            3\n2770         5  21.11051          1            3\n2771         5  21.10409          1            3\n2772         5  21.09060          1            3\n```\n\n\n:::\n:::\n\n\nWe can see the population that each row is linked to by the rownames. Here you can see 2767, 2768, 2769, etc. These each have a dispersal trait of 5 (because we didn;t vary this) slightly different temp_mean traits (because these evolved stochastically under a Brownian motion like model) and a temp width of 1 (again, we didn;t vary this in model 1).\n\nSo, if we want to map out the distribution of species 1 at timestep 0, we just need to link those cell names (267/268/etc) to the landscape object and make a raster. Why don;t we try and see what islands species 1 is found on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,2))\n\n# first plot the sialnds out from the landscape objet\npatch_xyz <- rast(lc$patch[,c(\"x\", \"y\", \"0\")], type=\"xyz\")\nplot(patch_xyz, main=\"Island Patches\", col=palette()[c(2,3,4,6)])\n\n# pull out values of the landscape where the species is found\nspecies1_xyz <- lc$patch[which(rownames(lc$patch) %in% rownames(species_t_0[[1]]$traits)), c(\"x\", \"y\", \"0\")]\n\n# turn it into a raster\nspecies1_xyz <- rast(species1_xyz, type=\"xyz\")\nspecies1_xyz <- extend(species1_xyz, patch_xyz)\nplot(species1_xyz, main= \"Species 1 Distribution\")\n```\n\n::: {.cell-output-display}\n![](Day2_Prac4_outputs_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n#### Linking the species object and phylogeny {.unnumbered}\n\nLets try and link the species trait data to the phylogeny to start learning something about what exactly took place during our simulation! Let's get the mean trait value of the temperature niche and also the islands that each species belongs too.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lets create a data frame\ndf <- data.frame(\"id\"= paste0(\"species\",sapply(species_t_0, function(x)x$id)),\n                 \"mean_temp\"=NA,\n                 \"island1\"=0,\n                 \"island2\"=0,\n                 \"island3\"=0,\n                 \"island4\"=0, \n                 \"island_start\"=NA)\n\n# take a look\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        id mean_temp island1 island2 island3 island4 island_start\n1 species1        NA       0       0       0       0           NA\n2 species2        NA       0       0       0       0           NA\n3 species3        NA       0       0       0       0           NA\n4 species4        NA       0       0       0       0           NA\n5 species5        NA       0       0       0       0           NA\n6 species6        NA       0       0       0       0           NA\n```\n\n\n:::\n\n```{.r .cell-code}\n# Use sapply on the species object to get their mean trait values\ndf$mean_temp <- sapply(species_t_0, function(x)mean(x$traits[, \"temp_mean\"], na.rm=T))\n\n# to get the island patch id values we'll use a for loop\nfor(i in 1:length(species_t_0)){\n  \n  # as before we get the lanscape values of each species\n  speciesi_xyz <- lc$patch[which(rownames(lc$patch) %in% rownames(species_t_0[[i]]$traits)), c(\"x\", \"y\", \"0\")]\n  \n  # then pull out the unique values (note that species might occur on more than one island)\n  islands <- unique(speciesi_xyz[, 3])\n  \n  # then if species are on the island, give that column a value of 1\n  df$island1[i] <- ifelse(1 %in% islands, 1, 0)\n  df$island2[i] <- ifelse(2 %in% islands, 1, 0)\n  df$island3[i] <- ifelse(3 %in% islands, 1, 0)\n  df$island4[i] <- ifelse(4 %in% islands, 1, 0)\n}\n\n# get the starting island from the traits object because we recorded this in the initialisation step\ndf$island_start <- sapply(species_t_0, function(x) unique(x$traits[, \"start_island\"]))\n```\n:::\n\n\nNow look again at the data frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        id mean_temp island1 island2 island3 island4 island_start\n1 species1  21.11335       0       0       1       0     3.000000\n2 species2  21.99631       0       0       0       1     4.000000\n3 species3  20.46238       1       1       0       0     1.000000\n4 species4  21.32327       1       0       0       0     1.485038\n5 species5  21.32634       1       0       0       0     1.485038\n6 species6  20.48675       1       0       0       0     1.000000\n```\n\n\n:::\n:::\n\n\nPlot out the continuously evolving temperature niche trait\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a named vector for the log of the temperature niche trait\ntemp_niche <- log(df$mean_temp)\nnames(temp_niche) <- df$id\n\n# plot it out with dots = trait\ndotTree(phy,temp_niche,ftype=\"i\")\n```\n\n::: {.cell-output-display}\n![](Day2_Prac4_outputs_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nNot much variation in that trait, due to the combined effects of trait homogenisation and a low rate of change. Lets plot the tip states of the islands on the phylogeny using the phytools package\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# format each island\nformatIsland <- function(island, phy=phy){\n  islandf <- as.factor(df[, island])\n  names(islandf) <- df$id\n  islandmat<-to.matrix(islandf,levels(islandf))\n  islandmat<-islandmat[phy$tip.label,]\n  return(list(islandf, islandmat))\n}\n\n\nplotTree(phy,ftype=\"i\",offset=1,fsize=0.9, xlim=c(0, 75))\n\ntiplabels(pie=formatIsland(island=\"island1\", phy=phy)[[2]],piecol=palette()[c(8,2)],cex=0.6, adj=12+1)\ntiplabels(pie=formatIsland(island=\"island2\", phy=phy)[[2]],piecol=palette()[c(8,3)],cex=0.6, adj=12+3)\ntiplabels(pie=formatIsland(island=\"island3\", phy=phy)[[2]],piecol=palette()[c(8,4)],cex=0.6, adj=12+5)\ntiplabels(pie=formatIsland(island=\"island4\", phy=phy)[[2]],piecol=palette()[c(8,6)],cex=0.6, adj=12+7)\n```\n\n::: {.cell-output-display}\n![](Day2_Prac4_outputs_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nInteresting. What do you notice about the distribution of species on islands? Could you predict which island each lineage began on?\n\nWe actually know which islands each lineage started on because we recorded this as a trait (we could also look at the past species objects to figure this out but we have used a short cut method).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,2))\nplotTree(phy,ftype=\"i\",offset=1,fsize=0.4, xlim=c(0, 75))\n\ntiplabels(pie=formatIsland(island=\"island1\", phy=phy)[[2]],piecol=palette()[c(8,2)],cex=0.6, adj=12+1)\ntiplabels(pie=formatIsland(island=\"island2\", phy=phy)[[2]],piecol=palette()[c(8,3)],cex=0.6, adj=12+3)\ntiplabels(pie=formatIsland(island=\"island3\", phy=phy)[[2]],piecol=palette()[c(8,4)],cex=0.6, adj=12+5)\ntiplabels(pie=formatIsland(island=\"island4\", phy=phy)[[2]],piecol=palette()[c(8,6)],cex=0.6, adj=12+7)\n# add the starting island as a fifth colum\ntiplabels(pie=formatIsland(island=\"island_start\", phy=phy)[[2]],piecol=palette()[c(2,3,4,6)],cex=0.6, adj=12+9)\n\n# add island plot\nplot(patch_xyz, main=\"Island Patches\", col=palette()[c(2,3,4,6)])\n```\n\n::: {.cell-output-display}\n![](Day2_Prac4_outputs_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nSo whats really apparent here is that the clade that originated on the green island has speciated allopatrically into the red island multiple times in the recent past. The same is true fro the red clade, however the deeper divergence between species9 and species3 have had enough time to recolonise both islands.\n\n#### Linking the species object, landscape, and phylogeny\n\nCommon spatial biodiversity analyses link information measured at the species level to maps of their distribution in space using presence-absence matrices or PAMs. PAMs typically are data frame with each row representing a site, could be an island or could be a grid cell, and each column representing a species. Values of 1 are given if the species is present in the site, if not a value of 0 is given.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# grid cell level PAM\n\n# create an empty data frame with the dimensions of species x sites\nPAM <- data.frame(matrix(0, nrow=nrow(lc$elevation), ncol=length(species_t_0)))\n\n# given names to rows and columns\nrownames(PAM) <- rownames(lc$elevation)\ncolnames(PAM) <- paste0(\"species\", sapply(species_t_0, function(x)x$id))\n\n# loop over species and add value of 1 to all sites the species is present\nfor(i in 1:length(species_t_0)){\n  \n  PAM[which(rownames(PAM) %in% names(species_t_0[[i]]$abundance)), i] <- 1\n}\n\n# how does it look?\nprint(PAM[1:10, 1:10])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   species1 species2 species3 species4 species5 species6 species7 species8\n1         0        0        0        0        0        0        0        0\n2         0        0        0        0        0        0        0        0\n3         0        0        0        0        0        0        0        0\n4         0        0        0        0        0        0        0        0\n5         0        0        0        0        0        0        0        0\n6         0        0        0        0        0        0        0        0\n7         0        0        0        0        0        0        0        0\n8         0        0        0        0        0        0        0        0\n9         0        0        0        0        0        0        0        0\n10        0        0        0        0        0        0        0        0\n   species9 species10\n1         0         0\n2         0         0\n3         0         0\n4         0         0\n5         0         0\n6         0         0\n7         0         0\n8         0         0\n9         0         0\n10        0         0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# we can estimate Phylogenetic diversity\npd_islands <- pd(PAM, phy)\n\n# we can also measure mean phylogenetic distance and mean nearest neighbour distance\nmpd_islands <- mpd(PAM, cophenetic(phy))\nmntd_islands <- mntd(PAM,cophenetic(phy))\n\n# link these back back with the landscape by joining to the lanscape lat/lons\ncommunity_phylo <- cbind(lc$elevation[, c(\"x\", \"y\")], pd_islands, mpd_islands, mntd_islands)\n\npar(mfrow=c(2,2))\nsr_ras <- rast(community_phylo[, c(\"x\", \"y\", \"SR\")], type=\"xyz\")\npd_ras <- rast(community_phylo[, c(\"x\", \"y\", \"PD\")], type=\"xyz\")\nmpd_ras <- rast(community_phylo[, c(\"x\", \"y\", \"mpd_islands\")], type=\"xyz\")\nmntd_ras <- rast(community_phylo[, c(\"x\", \"y\", \"mntd_islands\")], type=\"xyz\")\n\nplot(sr_ras, main=\"Species Richness\")\nplot(pd_ras, main=\"Phylogenetic Diversity\")\nplot(mpd_ras, main=\"Mean Phylogenetic Pairwise Distance\")\nplot(mntd_ras, main= \"Mean Nearest Neighbour Phylogenetic Distance\")\n```\n\n::: {.cell-output-display}\n![](Day2_Prac4_outputs_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n## Sensitivity analysis {.unnumbered}\n",
    "supporting": [
      "Day2_Prac4_outputs_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}